// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"
	"time"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (title, company, applied_at, updated_at, link, status)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, title, company, applied_at, updated_at, link, status
`

type CreateJobParams struct {
	Title     string
	Company   string
	AppliedAt time.Time
	UpdatedAt time.Time
	Link      string
	Status    string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.Title,
		arg.Company,
		arg.AppliedAt,
		arg.UpdatedAt,
		arg.Link,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.AppliedAt,
		&i.UpdatedAt,
		&i.Link,
		&i.Status,
	)
	return i, err
}
