// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Job struct {
	ID        int32
	Title     string
	Company   string
	AppliedAt time.Time
	UpdatedAt time.Time
	Link      string
	Status    string
}
