-- +goose Up
CREATE TABLE jobs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    applied_at TIMESTAMP NOT NULL, 
    updated_at TIMESTAMP NOT NULL,
    link TEXT NOT NULL,
    status TEXT NOT NULL
);

-- +goose Down
DROP TABLE jobs;
